//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using System;

namespace RoutingServer.ProxyCache {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCache.IProxy")]
    public interface IProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/getContracts", ReplyAction="http://tempuri.org/IProxy/getContractsResponse")]
        ProxyCache.JCDeceaux.Contract[] getContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/getContracts", ReplyAction="http://tempuri.org/IProxy/getContractsResponse")]
        System.Threading.Tasks.Task<ProxyCache.JCDeceaux.Contract[]> getContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/getStationsByContract", ReplyAction="http://tempuri.org/IProxy/getStationsByContractResponse")]
        ProxyCache.JCDeceaux.Station[] getStationsByContract(string contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/getStationsByContract", ReplyAction="http://tempuri.org/IProxy/getStationsByContractResponse")]
        System.Threading.Tasks.Task<ProxyCache.JCDeceaux.Station[]> getStationsByContractAsync(string contract);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyChannel : RoutingServer.ProxyCache.IProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyClient : System.ServiceModel.ClientBase<RoutingServer.ProxyCache.IProxy>, RoutingServer.ProxyCache.IProxy {
        
        public ProxyClient() {
        }
        
        public ProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProxyCache.JCDeceaux.Contract[] getContracts() {
            return base.Channel.getContracts();
        }
        
        public System.Threading.Tasks.Task<ProxyCache.JCDeceaux.Contract[]> getContractsAsync() {
            return base.Channel.getContractsAsync();
        }
        
        public ProxyCache.JCDeceaux.Station[] getStationsByContract(string contract) {
            return base.Channel.getStationsByContract(contract);
        }
        
        public System.Threading.Tasks.Task<ProxyCache.JCDeceaux.Station[]> getStationsByContractAsync(string contract) {
            return base.Channel.getStationsByContractAsync(contract);
        }

    }
    public class JCDeceaux
    {
        [DataContract]
        public class Contract
        {
            [DataMember]
            public string name { get; set; }
            [DataMember]
            public int number { get; set; }
            [DataMember]
            public string[] cities { get; set; }
        }
        [DataContract]
        public class Station
        {
            [DataMember]
            public int number { get; set; }
            [DataMember]
            public string name { get; set; }
            [DataMember]
            public Position position { get; set; }
            [DataMember]
            public TotalStands totalStands { get; set; }
        }
        public class Position
        {
            [DataMember]
            public Double latitude { get; set; }
            [DataMember]
            public Double longitude { get; set; }
            public Position(double lat, double lon)
            {
                latitude = lat;
                longitude = lon;
            }
            public Position() { }

        }
        [DataContract]
        public class TotalStands
        {
            [DataMember]
            public Availabilities availabilities { get; set; }
        }
        [DataContract]
        public class Availabilities
        {
            [DataMember]
            public int bikes { get; set; }
            [DataMember]
            public int stands { get; set; }

        }
    }
}
